### ISSUE TITLE
Bundle into one HTML file

### ISSUE THREAD

**Issue by PeWu** [develancer/topola-webpack#1]
Nice work! It makes it much easier to deploy and share a self-contained interactive family tree.

Do you think it would be possible to bundle everything into one big HTML file? This way, you could just  send someone a single file and they would be able to see the interactive chart.

**Comment by develancer** [comment]
Good idea! I haven't consider it initially, as I didn't want to prevent the browser from caching the JS file. However, in the end it does not matter whether the server will return 304 Not Modified for the JS file or for the all-in-one HTML file.

I think I'll be able to accomplish this with html-webpack-plugin and html-webpack-inline-source-plugin.

**Comment by redstreet** [comment]
This would be a "nice to have" for me too. I use [staticrypt](https://robinmoisson.github.io/staticrypt/), which only works on a single html file. It's easy to get around by cat'ing `main.js` into `index.html`, so it's not a biggie.

Great project, thank you!

**Comment by develancer** [comment]
Certainly will do. Cannot commit on any timeframe, though.

**Comment by redstreet** [comment]
Of course, this is just a nice to have, and is very low priority IMHO.

**Comment by develancer** [comment]
It took me some time to find a slot for it, but here it is. The current version (master) generates a single HTML file.

**Comment by redstreet** [comment]
Works great, thank you again!
