### ISSUE TITLE
Need to refresh page on each click

### ISSUE THREAD

**Issue by redstreet** [develancer/topola-webpack#2]
Everything works great, except for one detail: whenever I double click on a node, I have to hit my browser's refresh button before the new results will display. Tried in Firefox, Edge, and IE on desktop, and on Chrome on Android, same issue occurs. Is this to be expected? Am I doing something wrong?

This is an awesome project, BTW. Everything works very smoothly, and this is exactly what I was looking for. Thank you for making it!

**Comment by PeWu** [comment]
I can't reproduce your problem. Maybe the problem is connected to the input file? Can you try it with this file: https://github.com/PeWu/topola/blob/master/demo/data/family.ged ?

**Comment by redstreet** [comment]
I was running an old version of nodejs (10.xx). I was forced to update it for reasons unrelated to topola-webpack, and the problems completely disappeared. Works fine on every browser now, desktop and mobile, which it clearly didn't previously.

I didn't have a chance to try your family.ged with my old setup (works fine with the new setup), and don't think it's worth risking my setup now to confirm if that was indeed the problem :).

Closing this ticket. Thanks bunch for the response!

**Comment by redstreet** [comment]
Spoke too soon. Problem still occurs. See here:
![needrefresh](https://user-images.githubusercontent.com/691755/142986613-9f695795-8441-4410-bad8-e8085f0681ea.gif)

**Comment by develancer** [comment]
Do I understand correctly that the problem is that the hidden nodes (e.g. Nilüfer in the example above) are not being shown when they should (e.g. when we click on Mervyn)? It reason of this issue may be that these nodes are somehow filtered when fetching nodes for the initial view and therefore cannot be shown later.

@PeWu I wonder whether this is a problem with [Topola](https://github.com/PeWu/topola) itself or only here.

**Comment by redstreet** [comment]
That's correct.

I'm curious, is this not something that you experience or have been able to reproduce? The above was on stock Firefox on a stock Windows 10 machine, and I see the same on Edge. So I figured this would be easy to reproduce.

**Comment by redstreet** [comment]
FWIW, when using Topola, I don't experience this. Happens only when using topola-webpack.

**Comment by develancer** [comment]
@redstreet Unfortunately, I am not able to reproduce this issue.

Please check if you see the same behaviour with the example prepared [here](https://rozan.ski/test-topola-webpack/). It is built with npm version 6.14.4, should that matter. In my setup (Firefox 90 under Ubuntu) it works fine.

**Comment by redstreet** [comment]
@develancer, thanks for the response. That example you pointed to works 100% fine for me on all browsers and platforms. The problem clearly shows up on all browsers when I build the same example above. So I think it's safe to assume this problem is not on the client side.

Unfortunately, I'm unable to reproduce the issue consistently. The next time it reproduces, I'll do a diff of the output to see if that sheds light. Thanks much for the leads!
